[build-system]
requires = ["setuptools>=72,<81", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "aio_uring"
version = "0.4.0"
requires-python = ">=3.12"
authors = [
  {name = "Aivazian Artur", email = "arcanwork@gmail.com"},
  {email = "aivazian.artur.artakovich@gmail.com"},
]
maintainers = [
  {name = "Aivazian Artur", email = "arcanwork@gmail.com"}
]
description = "High-Performance io_uring wrapper for Python"
readme = "README.md"
license = {file = "LICENSE"}

[project.urls]
Homepage = "https://github.com/AivazianArtur/aio_uring"
Documentation = "https://aivazianartur.github.io/aio_uring/"
Repository = "https://github.com/AivazianArtur/aio_uring.git"
Issues = "https://github.com/AivazianArtur/aio_uring/issues"
Changelog = "https://github.com/AivazianArtur/aio_uring/blob/main/CHANGELOG.md"

[tool.setuptools]
packages = ["aio_uring_stubs"]

[tool.setuptools.package-data]
"aio_uring_stubs" = ["py.typed", "*.pyi"]

[tool.cibuildwheel]
build = "cp312-* cp313-* cp314-*"
skip = "*-musllinux_*"


test-command = "python -c \"import aio_uring\""
