name: CI

on:
  push:
  pull_request:

jobs:
  linter:
    uses: ./.github/workflows/linter.yml

  docs:
    uses: ./.github/workflows/docs.yml

  tests:
    uses: ./.github/workflows/tests.yml

  whels:
    uses: ./.github/workflows/wheels.yml
