name: sanitizers

on:
  push:
    branches:
      - main
  pull_request:
  workflow_call:

jobs:
  sanitizers-asan_ubsan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: make dev-deps

      - name: Run ASan + UBSan tests
        run: make test-all-asan

  sanitizers-tsan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: make dev-deps

      - name: Run TSan tests
        run: |
          TSAN_LIB=$(ldconfig -p | awk '/libtsan\.so/ {print $NF; exit}')
          if [ -z "$TSAN_LIB" ]; then TSAN_LIB="/usr/lib/x86_64-linux-gnu/libtsan.so.2"; fi
          
          make test-all-asan \
            ASAN_CFLAGS="-O0 -g3 -fsanitize=thread -fno-omit-frame-pointer" \
            ASAN_LDFLAGS="-fsanitize=thread" \
            ASAN_LIB="$TSAN_LIB"

  sanitizers-msan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: make dev-deps

      - name: Run MSan tests
        run: |
          make test-all-asan \
            CC=clang \
            ASAN_CFLAGS="-O0 -g3 -fsanitize=memory -fno-omit-frame-pointer" \
            ASAN_LDFLAGS="-fsanitize=memory" \
            ASAN_LIB="" # MSan обычно линкуется статически или не требует LD_PRELOAD
