name: tests

on:
  push:
    branches:
      - main
  pull_request:
  workflow_call:

jobs:
  test-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: make dev-deps

      - name: Run Python tests (pytest)
        run: make test-python

  test-c:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: make dev-deps

      - name: Run C-level tests
        run: make test-c-files test-c-sockets test-c-buffers test-c-registry
